# Generated by Django 4.2.5 on 2023-09-27 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_product_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='sizes',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 20, 17, 48, 21167)),
        ),
    ]
