# Generated by Django 4.2.5 on 2023-09-27 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_sizes_product_size_alter_product_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 20, 21, 10, 657208)),
        ),
    ]
