# Generated by Django 4.2.5 on 2023-09-30 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 10, 1, 2, 0, 30, 382143)),
        ),
    ]
